version: '3.8'

services:
  shazusoft-whatsapp-agent:
    build: .
    container_name: shazusoft_whatsapp_agent
    restart: always
    ports:
      - "3001:3001"
      - "5005:5005"
    volumes:
      - ./gateway/auth_info:/app/gateway/auth_info
    env_file:
      - .env
