/**
 * Shazu Soft Technologies - WhatsApp Gateway
 * Built with @whiskeysockets/baileys & Express
 * Direct WhatsApp Web Multi-Device Connection with Zero Third-Party SaaS Fees
 */

const { default: makeWASocket, DisconnectReason, useMultiFileAuthState, fetchLatestBaileysVersion } = require('@whiskeysockets/baileys');
const express = require('express');
const QRCode = require('qrcode');
const qrcodeTerminal = require('qrcode-terminal');
const pino = require('pino');
const http = require('http');
const path = require('path');
const fs = require('fs');

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3001;
const PYTHON_WEBHOOK_URL = process.env.PYTHON_WEBHOOK_URL || 'http://127.0.0.1:5005/webhook';
const AUTH_DIR = path.join(__dirname, 'auth_info');

let sock = null;
let currentQR = null;
let connectionStatus = 'initializing'; // initializing | qr_ready | connected | reconnecting
let connectedUser = null;

// In-memory circular log buffer (last 100 events)
const activityLogs = [];
function addLog(type, message, details = null) {
  const timestamp = new Date().toLocaleTimeString('en-US', { hour12: false });
  const entry = {
    id: Date.now() + Math.random().toString(36).substr(2, 4),
    time: timestamp,
    type,
    message,
    details
  };
  activityLogs.push(entry);
  if (activityLogs.length > 100) activityLogs.shift();

  const prefix = `[${timestamp}] [${type}]`;
  console.log(`${prefix} ${message}`);
}

// Track IDs of messages sent by this bot so we NEVER reply to our own messages
const botSentMessageIds = new Set();
// Track recently processed message IDs to prevent duplicates
const processedMessageIds = new Set();

async function connectToWhatsApp() {
  addLog('SYSTEM', 'Initializing WhatsApp Multi-Device session from ' + AUTH_DIR);
  
  if (!fs.existsSync(AUTH_DIR)) {
    fs.mkdirSync(AUTH_DIR, { recursive: true });
  }

  const { state, saveCreds } = await useMultiFileAuthState(AUTH_DIR);
  const { version, isLatest } = await fetchLatestBaileysVersion();
  addLog('SYSTEM', `Using Baileys WA version v${version.join('.')}, isLatest: ${isLatest}`);

  sock = makeWASocket({
    version,
    auth: state,
    logger: pino({ level: 'silent' }),
    printQRInTerminal: false,
    generateHighQualityLinkPreview: true,
    browser: ['Shazu Soft Technologies', 'Chrome', '124.0.0']
  });

  sock.ev.on('creds.update', saveCreds);

  sock.ev.on('connection.update', async (update) => {
    const { connection, lastDisconnect, qr } = update;

    if (qr) {
      currentQR = qr;
      connectionStatus = 'qr_ready';
      addLog('QR', 'New QR Code generated. Scan in browser at http://localhost:3001/qr');
      console.log('\n======================================================');
      console.log('>>> SCAN THIS QR CODE IN WHATSAPP (Linked Devices) <<<');
      console.log('======================================================\n');
      qrcodeTerminal.generate(qr, { small: true });
      console.log('\nAlternatively, view QR code in browser at: http://localhost:3001/qr\n');
    }

    if (connection === 'close') {
      const statusCode = lastDisconnect?.error?.output?.statusCode;
      const shouldReconnect = statusCode !== DisconnectReason.loggedOut;
      connectionStatus = shouldReconnect ? 'reconnecting' : 'logged_out';
      addLog('CONN', `Connection closed (code: ${statusCode || 'unknown'}). Reconnecting: ${shouldReconnect}`);

      if (shouldReconnect) {
        setTimeout(connectToWhatsApp, 3000);
      } else {
        addLog('CONN', 'Session logged out. Clearing credentials...');
        currentQR = null;
        connectedUser = null;
        fs.rmSync(AUTH_DIR, { recursive: true, force: true });
        setTimeout(connectToWhatsApp, 2000);
      }
    } else if (connection === 'open') {
      connectionStatus = 'connected';
      currentQR = null;
      connectedUser = sock.user;
      addLog('CONN', `SUCCESS! WhatsApp Connected as: ${sock.user?.id || 'Connected'}`);
    }
  });

  // Handle incoming messages
  sock.ev.on('messages.upsert', async ({ messages, type }) => {
    if (!messages || !messages.length) return;

    for (const msg of messages) {
      const msgId = msg.key?.id;
      if (!msgId) continue;

      // 1. Ignore if already processed or if generated by this bot
      if (processedMessageIds.has(msgId) || botSentMessageIds.has(msgId)) {
        continue;
      }
      processedMessageIds.add(msgId);
      if (processedMessageIds.size > 2000) {
        const first = processedMessageIds.values().next().value;
        processedMessageIds.delete(first);
      }

      const remoteJid = msg.key?.remoteJid || '';
      // Ignore broadcast status updates, channels, and group chats
      if (
        remoteJid === 'status@broadcast' || 
        remoteJid.endsWith('@g.us') || 
        remoteJid.endsWith('@newsletter') || 
        remoteJid.includes('@broadcast')
      ) {
        continue;
      }

      // 2. Extract message text
      const messageText = 
        msg.message?.conversation || 
        msg.message?.extendedTextMessage?.text || 
        msg.message?.imageMessage?.caption || 
        msg.message?.videoMessage?.caption || 
        '';

      if (!messageText || !messageText.trim()) {
        continue;
      }

      const cleanText = messageText.trim();
      const isFromMe = Boolean(msg.key?.fromMe);
      const myId = sock.user?.id ? sock.user.id.split(':')[0] : '';
      const isSelfChat = remoteJid.includes(myId) || (sock.user?.lid && remoteJid === sock.user.lid);

      if (isFromMe) {
        if (isSelfChat) {
          // Self-Test Mode: User messaged themselves on the connected phone!
          addLog('SELF-TEST', `Detected self-test from phone owner: "${cleanText}"`);
          forwardToPythonAndReply(remoteJid, myId, 'Phone Owner (Self-Test)', cleanText);
        } else {
          // Human owner sent message to an external client
          addLog('HUMAN', `Owner replied to ${remoteJid}. AI will not interfere.`);
        }
        continue;
      }

      // Normal Inbound Customer Message
      const senderPhone = remoteJid.replace(/[^0-9]/g, '');
      const senderName = msg.pushName || 'Prospective Client';
      addLog('INBOUND', `From ${senderPhone} (${senderName}): "${cleanText}"`);

      forwardToPythonAndReply(remoteJid, senderPhone, senderName, cleanText);
    }
  });
}

// Forward message to Python AI Engine and send reply via WhatsApp
function forwardToPythonAndReply(jid, phone, name, text) {
  const payload = JSON.stringify({
    phone: phone,
    name: name,
    message: text
  });

  const url = new URL(PYTHON_WEBHOOK_URL);
  const options = {
    hostname: url.hostname,
    port: url.port,
    path: url.pathname,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(payload),
      'Connection': 'close'
    }
  };

  const req = http.request(options, (res) => {
    let responseData = '';
    res.on('data', (chunk) => { responseData += chunk; });
    res.on('end', async () => {
      try {
        if (res.statusCode !== 200) {
          addLog('ERROR', `Python engine returned HTTP ${res.statusCode}: ${responseData.substring(0, 120)}`);
          return;
        }
        const json = JSON.parse(responseData);
        const replyText = json.reply;

        if (replyText && sock) {
          addLog('AI-REPLY', `Generated reply for ${name} (${replyText.length} chars). Sending...`);

          // 1. Simulate human typing presence
          try {
            await sock.sendPresenceUpdate('composing', jid);
          } catch (e) {}

          // 2. Short natural typing delay (2 seconds)
          await new Promise(r => setTimeout(r, 2000));

          // 3. Clear typing indicator
          try {
            await sock.sendPresenceUpdate('paused', jid);
          } catch (e) {}

          // 4. Send message
          const sent = await sock.sendMessage(jid, { text: replyText });
          if (sent?.key?.id) {
            botSentMessageIds.add(sent.key.id);
            if (botSentMessageIds.size > 2000) {
              const first = botSentMessageIds.values().next().value;
              botSentMessageIds.delete(first);
            }
          }
          addLog('DELIVERED', `Reply delivered successfully to ${phone}!`);
        } else {
          addLog('AI-WARN', `No reply returned by AI engine for ${phone}`);
        }
      } catch (err) {
        addLog('ERROR', `Failed parsing Python response: ${err.message}`);
      }
    });
  });

  req.on('error', (err) => {
    addLog('ERROR', `Failed to reach Python AI Webhook at ${PYTHON_WEBHOOK_URL}: ${err.message}`);
  });

  req.write(payload);
  req.end();
}

// REST API Endpoints
app.get('/status', (req, res) => {
  res.json({
    status: connectionStatus,
    user: connectedUser,
    hasQR: !!currentQR
  });
});

app.get('/api/logs', (req, res) => {
  res.json({
    status: connectionStatus,
    user: connectedUser?.id || null,
    logs: activityLogs
  });
});

// Proxy endpoint to get leads from Neon PostgreSQL via Python
app.get('/api/leads', (req, res) => {
  const url = new URL(PYTHON_WEBHOOK_URL);
  const options = {
    hostname: url.hostname,
    port: url.port,
    path: '/api/leads',
    method: 'GET'
  };

  const pyReq = http.request(options, (pyRes) => {
    let responseData = '';
    pyRes.on('data', (chunk) => { responseData += chunk; });
    pyRes.on('end', () => {
      try {
        res.json(JSON.parse(responseData));
      } catch (e) {
        res.status(500).json({ error: 'Failed parsing leads data' });
      }
    });
  });

  pyReq.on('error', (err) => {
    res.status(500).json({ error: 'Failed fetching leads: ' + err.message });
  });

  pyReq.end();
});

// Proxy endpoint to get system stats from Neon PostgreSQL via Python
app.get('/api/stats', (req, res) => {
  const url = new URL(PYTHON_WEBHOOK_URL);
  const options = {
    hostname: url.hostname,
    port: url.port,
    path: '/api/stats',
    method: 'GET'
  };

  const pyReq = http.request(options, (pyRes) => {
    let responseData = '';
    pyRes.on('data', (chunk) => { responseData += chunk; });
    pyRes.on('end', () => {
      try {
        res.json(JSON.parse(responseData));
      } catch (e) {
        res.status(500).json({ error: 'Failed parsing stats data' });
      }
    });
  });

  pyReq.on('error', (err) => {
    res.status(500).json({ error: 'Failed fetching stats: ' + err.message });
  });

  pyReq.end();
});

// Endpoint to disconnect / unlink WhatsApp session
app.post('/api/disconnect', async (req, res) => {
  addLog('SYSTEM', 'Disconnect requested. Unlinking WhatsApp session...');
  try {
    if (sock) {
      try {
        await sock.logout();
      } catch (e) {}
      try {
        sock.end(new Error('User disconnected'));
      } catch (e) {}
    }
  } catch (err) {}

  connectionStatus = 'initializing';
  connectedUser = null;
  currentQR = null;

  // Clear credentials folder so next connection requests fresh QR
  try {
    if (fs.existsSync(AUTH_DIR)) {
      fs.rmSync(AUTH_DIR, { recursive: true, force: true });
    }
  } catch (err) {
    console.error('Error clearing auth dir:', err);
  }

  // Reinitialize socket to generate fresh QR code
  setTimeout(() => {
    connectToWhatsApp();
  }, 1000);

  res.json({ success: true, message: 'WhatsApp session disconnected. New QR code is generating...' });
});

// Endpoint to test AI Brain directly from browser UI
app.post('/api/test-chat', (req, res) => {
  const { message, name, phone } = req.body;
  const payload = JSON.stringify({
    phone: phone || '919876543210',
    name: name || 'Test User',
    message: message || 'Hi'
  });

  const url = new URL(PYTHON_WEBHOOK_URL);
  const options = {
    hostname: url.hostname,
    port: url.port,
    path: url.pathname,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(payload),
      'Connection': 'close'
    }
  };

  const pyReq = http.request(options, (pyRes) => {
    let responseData = '';
    pyRes.on('data', (chunk) => { responseData += chunk; });
    pyRes.on('end', () => {
      try {
        const json = JSON.parse(responseData);
        addLog('TEST-CHAT', `Web tester sent: "${message}" -> Got response (${(json.reply || '').length} chars)`);
        res.json(json);
      } catch (e) {
        res.status(500).json({ error: 'Failed to parse AI response' });
      }
    });
  });

  pyReq.on('error', (err) => {
    res.status(500).json({ error: 'Could not contact Python AI Brain: ' + err.message });
  });

  pyReq.write(payload);
  pyReq.end();
});

// Main Interactive Dashboard & QR Page
app.get(['/', '/qr'], async (req, res) => {
  if (connectionStatus === 'connected') {
    const rawId = connectedUser?.id || 'Connected Account';
    const displayPhone = rawId.split(':')[0] || rawId;

    try {
      const templatePath = path.join(__dirname, 'dashboard.html');
      let html = fs.readFileSync(templatePath, 'utf-8');
      html = html.replace(/{{DISPLAY_PHONE}}/g, displayPhone);
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.send(html);
    } catch (e) {
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.send(`<h2>WhatsApp Agent Connected as ${displayPhone}</h2>`);
    }
  }

  if (!currentQR) {
    return res.send(`
      <body style="font-family:sans-serif; text-align:center; padding:50px; background:#0f172a; color:#fff;">
        <h2>Connecting to WhatsApp Gateway...</h2>
        <p style="color:#94a3b8; margin-top:10px;">Generating session or QR code. Please wait 3 seconds...</p>
        <script>setTimeout(() => location.reload(), 3000);</script>
      </body>
    `);
  }

  try {
    const qrDataUrl = await QRCode.toDataURL(currentQR, { width: 280, margin: 2 });
    res.send(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Shazu Soft WhatsApp Agent - Scan QR</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; text-align:center; padding: 40px 20px; background: #0b1329; color: #f8fafc; }
          .card { max-width: 420px; margin: 0 auto; background: #111e38; padding: 30px; border-radius: 24px; box-shadow: 0 10px 30px rgba(0,0,0,0.4); border: 1px solid #1e293b; }
          .qr-img { margin: 20px auto; border-radius: 12px; border: 4px solid #fff; display: block; }
          .badge { background: rgba(16, 185, 129, 0.2); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.4); padding: 4px 12px; border-radius: 9999px; font-weight: bold; font-size: 11px; text-transform: uppercase; }
          ol { text-align: left; font-size: 13px; line-height: 1.8; color: #94a3b8; padding-left: 20px; margin-top: 15px; }
        </style>
      </head>
      <body>
        <div class="card">
          <span class="badge">Shazu Soft WhatsApp AI Gateway</span>
          <h2 style="margin: 15px 0 5px;">Scan QR to Link WhatsApp</h2>
          <p style="font-size: 13px; color: #94a3b8; margin-bottom: 20px;">Link your dedicated phone number to start the 24/7 AI agent.</p>
          
          <img src="${qrDataUrl}" alt="Scan WhatsApp QR Code" class="qr-img" width="280" height="280" />

          <ol>
            <li>Open WhatsApp on your phone</li>
            <li>Tap <strong>Settings</strong> (or 3 dots) &gt; <strong>Linked Devices</strong></li>
            <li>Tap <strong>Link a Device</strong> and point your camera here</li>
          </ol>
        </div>

        <script>
          setInterval(async () => {
            try {
              const res = await fetch('/status');
              const data = await res.json();
              if (data.status === 'connected') {
                location.reload();
              }
            } catch(e) {}
          }, 2500);
        </script>
      </body>
      </html>
    `);
  } catch (err) {
    res.status(500).send("Error generating QR code: " + err.message);
  }
});

app.post('/send', async (req, res) => {
  const { phone, message } = req.body;
  if (!sock || connectionStatus !== 'connected') {
    return res.status(503).json({ error: 'WhatsApp gateway is not connected' });
  }

  try {
    const cleanPhone = phone.replace(/[^0-9]/g, '');
    const jid = `${cleanPhone}@s.whatsapp.net`;
    const sent = await sock.sendMessage(jid, { text: message });
    if (sent?.key?.id) botSentMessageIds.add(sent.key.id);
    addLog('MANUAL-SEND', `Manually sent message to ${cleanPhone}`);
    res.json({ success: true, deliveredTo: jid });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Start Express Server & WhatsApp Connection
app.listen(PORT, () => {
  addLog('SYSTEM', `WhatsApp Gateway running at http://localhost:${PORT}`);
  connectToWhatsApp();
});
